apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongodb
